### ISSUE TITLE
Wrong project name

### ISSUE THREAD

**Issue by tredoe** [gobeam/stringy#2]
If the package name is "stringy", the project name must be named like it ("stringy"), not "Stringy".

**Comment by gobeam** [comment]
Okay @tredoe project name police it was named after [danielstjules/Stringy](https://github.com/danielstjules/Stringy) because I took inspiration from that package. So nothing wrong with naming it that way.

**Comment by tredoe** [comment]
The real issue is because when someone import your project using `import "github.com/gobeam/Stringy"`, then the public functions and constants can not be called using "Stringy.SomeFunc()".

That's the reason why all projects in Go are named in lower case.

**Comment by gobeam** [comment]
@tredoe repo name has been updated. Thanks.
