### ISSUE TITLE
CPU usage optimization: removed regexp recompelation

### ISSUE THREAD

**Issue by alexey-slivkin** [gobeam/stringy#27]
I use a lot of CamelCase function calls, and in the pprof report I see that the lion's share of the CPU is spent on compiling constant regular expressions.

I would like remove re-compilation of regular expressions on each request for helper functions. 

Soulution:
https://github.com/gobeam/stringy/pull/26

**Comment by gobeam** [comment]
@alexey-slivkin great I will merge it
