### ISSUE TITLE
Prefix and Suffix

### ISSUE THREAD

**Issue by AkselMeola** [gobeam/stringy#5]
**Is your feature request related to a problem? Please describe.**
For example when working with path uris you may want to end or start the path with `/`, except when it already does not have such prefix or suffix. This may be necessary to normalize base paths coming from user input or from configs. 
 
**Describe the solution you'd like**
A conditional `Prefix()` and `Suffix()` method that would add suffix/prefix in case it does not exist. 
In some languages/libraries these are also called str_start, str_cap, str_finish etc.. 

**Describe alternatives you've considered**
I have done this in couple of projects, but I'd rather use some good existing/common library instead of copy-pasting utilities package from project to project.

**Additional context**
I'd make a PR, but it requires an issue to exist as I read from contributions guidelines.
 
Proposed code examples:
```golang

import "strings"

// Prepend a string to a string if it does not already start with same string
func Prefix(str, prefix string) string {
	if strings.HasPrefix(str, prefix) {
		return str
	}

	return prefix + str
}

// Append a string to string if it does not already end with same string
func Suffix(str, suffix string) string {
	if strings.HasSuffix(str, suffix) {
		return str
	}

	return str + suffix
}
```

**Comment by gobeam** [comment]
> **Is your feature request related to a problem? Please describe.**
> For example when working with path uris you may want to end or start the path with `/`, except when it already does not have such prefix or suffix. This may be necessary to normalize base paths coming from user input or from configs.
> 
> **Describe the solution you'd like**
> A conditional `Prefix()` and `Suffix()` method that would add suffix/prefix in case it does not exist.
> In some languages/libraries these are also called str_start, str_cap, str_finish etc..
> 
> **Describe alternatives you've considered**
> I have done this in couple of projects, but I'd rather use some good existing/common library instead of copy-pasting utilities package from project to project.
> 
> **Additional context**
> I'd make a PR, but it requires an issue to exist as I read from contributions guidelines.
> 
> Proposed code examples:
> 
> ```go
> import "strings"
> 
> // Prepend a string to a string if it does not already start with same string
> func Prefix(str, prefix string) string {
> 	if strings.HasPrefix(str, prefix) {
> 		return str
> 	}
> 
> 	return prefix + str
> }
> 
> // Append a string to string if it does not already end with same string
> func Suffix(str, suffix string) string {
> 	if strings.HasSuffix(str, suffix) {
> 		return str
> 	}
> 
> 	return str + suffix
> }
> ```

You're welcome to make this  PR as a new feature.
