### ISSUE TITLE
Improve performance, a lot of malloc is being used

### ISSUE THREAD

**Issue by aruizeac** [gobeam/stringy#7]
**Describe the bug**
Currently, some basic functionality such as snake case formatting uses a lot of memory allocation (up to 70 malloc/op).

It is really a let down having that kind of performance for a helper library.

**To Reproduce**
1. Call function 'SnakeCase().String()' using go's benchmark.

**Expected behavior**
Reduce mallocs.

**Comment by gobeam** [comment]
@maestre3d I will surely work to optimize it but if you have any better solution you're welcome to create PR.
